config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#index'

  get '/show', to: 'home#show'

  resources :item_users
  resources :items
  resources :cupboards
  resources :users
  resources :user_sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]


  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  get '/sign_up', to: 'users#new', as: :sign_up #is this old/needed as xxxx?
  get '/new_cupboard', to: 'cupboards#new'
  put '/edit_cupboard', to: 'cupboards#edit'
 
 

  get 'renew/:id' => 'item_users#renew'
  get 'return/:id' => 'item_users#disable'


 
end

app/models/cupboard.rb
class Cupboard < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :users


  validates :name, presence: true
end

app/controllers/cupboards_controller.rb
class CupboardsController < ApplicationController
  before_action :current_user_active
  before_action :set_cupboard, except: [:new, :create]


  def new
    @cupboard = Cupboard.new
    @cupboards = Cupboard.all
    @user = current_user
    @users = User.all 
  end

  def create
    @cupboard = Cupboard.new(cupboard_params)
      if @cupboard.save
        flash[:notice] = "Cupboard successfuly added."
        redirect_to new_cupboard_path
      else
        render :new
      end
  end

  def show  
    @cupboards = Cupboard.all   
  end

  def edit

  end


  def update
   if @cupboard.update(cupboard_params);
     redirect_to new_cupboard_path, notice: 'Cupboard was successfully updated.'
   else
     render :edit
   end
  end

  def destroy
       @cupboard.destroy
       redirect_to new_cupboard_path, notice: 'Cupboard was successfully destroyed.'
  end


    private

    def cupboard_params
      params.require(:cupboard).permit( :name, :description)
    end 

    def set_cupboard
    @cupboard = Cupboard.find(params[:id])
    end

end

app/helpers/cupboards_helper.rb
module CupboardsHelper
end

app/views/cupboards/edit.html.erb
<div class="page-header"><h1>Add Cupboard</h1></div>
<div class="jumbotron">
<%= form_for @cupboard, method: "PUT" do |f| %>
	<% if @cupboard.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@cupboard.errors.count, "error") %> prohibited this user from being saved:</h2>

		<ul>
			<% @cupboard.errors.full_messages.each do |message| %>
		<li><%= message %></li>
	<% end %>
		</ul>
	</div>
<% end %>

	<div class="box-body">
	<div class="form-group">
		<label>Cupboard Name</label>
			<%= f.text_field :name, autocomplete: "off", placeholder: "Enter Cupboard Name", class: "form-control", required: true %>
	</div>
	<div class="form-group">
		<label>Description</label>
		<%= f.text_field :description, autocomplete: "off", placeholder: "Enter Cupboard Description", class: "form-control", required: true %>
	</div>
	
                   

	<!-- /.box-body -->
	<div class="box-footer">
		<%= f.submit "Update", class: "btn btn-primary"%>
	</div>
<% end %>

</div>

app/views/cupboards/new.html.erb
<div class="page-header" style="align: centre"><h1>Cupboards</h1></div>
<div class="col-md-12">
<div class="col-md-6">
<div class="jumbotron">
<%= form_for @cupboard do |f| %>
 
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <%= f.submit 'Add Cupboard', class: 'btn btn-primary btn-lg' %>
<% end %>
</div>
</div>

<div class="col-md-6">
  <table class="table table-bitem_usersed table-hover">
	  <tr>
	    <th>Cupboard Name</th>
	    <th>Cupboard Description</th>
	    <th>
	      <i class="ion ion-edit"></i>
	    </th>
	    <th>
	      <i class="ion ion-trash-b"></i>
	    </th>
	  </tr>
	  <% @cupboards.each do |cupboard| %>
	  <tr>
	  	<!--Would add sorting-->
	    <td><%= cupboard.name %></td>
	    <td><%= cupboard.description %></td>
	    <td><%= link_to "", edit_cupboard_path(cupboard.id), { class: "ion ion-edit"} %></td>
	    <td><%= link_to "", cupboard_path(cupboard.id) ,method: :delete , data: { confirm: 'Are you sure that you would like to delete this cuboard? All items in the cupboard will be destroyed!' },  class: "ion ion-trash-b" %></td>
	  </tr>

	  <% end %>
	</table>

		   <%= render 'shared/errors', object: @cupboard %>
</div>
</div>