config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#index'

  get '/show', to: 'home#show'

  resources :item_users
  resources :items
  resources :cupboards
  resources :users
  resources :user_sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]


  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  get '/sign_up', to: 'users#new', as: :sign_up #is this old/needed as xxxx?
  get '/new_cupboard', to: 'cupboards#new'
  put '/edit_cupboard', to: 'cupboards#edit'
 
 

  get 'renew/:id' => 'item_users#renew'
  get 'return/:id' => 'item_users#disable'


 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :current_user_active


    def show  
      @user = current_user
      @item_users = ItemUser.all
      @items = Item.all
      @cupboards = Cupboard.all
      @users = User.all 
      #.includes(:XXX) preloads requested data 1 query at database not multiple!!
      @active = ItemUser.active?.includes(:item)     
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/show.html.erb
<body>
  <div class="content-wrapper">
    <section class="content">
      <div class="row">
        <div class="col-md-9">
          <div class="box">
            <div class="box-header with-bitem_users">
              <h3 class="box-title">On loan (<%= @active.count %>)</h3>
            </div>
            <div class="box-body">
              <table class="table table-bitem_usersed table-hover">
                <thead>
                  <tr>
                    <th>Description</th>
                    <th>Cupboard</th>
                    <th>Qty</th>
                    <th>Return By</th>
                    <th>Borrowed By</th>
                    <th>
                      <i class="ion ion-log-in"></i>
                    </th>
                    <th>
                      <i class="ion ion-loop"></i>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <% @active.each do |item_user| %>
                  <tr>
                    <td>
                      <%= item_user.item.name %>
                   </td>
                   <td>
                      <%= item_user.item.cupboard_id %>
                   </td>                     
                    <td>
                      <%= item_user.quantity %>                        
                    </td>                      
                    <td>
                      <%= item_user.return_date %>
                    </td>     
                    <td>
                      <%= item_user.user.name %>
                    </td>
                    <td>
                      <%= link_to "", { :controller => :item_users, :action => :disable, :id => item_user.id }, { class: "ion ion-log-in"} %>
                    </td>
                    <td>
                      <%= link_to "", { :controller => :item_users, :action => :renew, :id => item_user.id }, { class: "ion ion-loop"} %>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-9">
        <div class="box">
          <div class="box-header with-bitem_users">
            <h3 class="box-title">Users (<%= @users.count %>)</h3>
          </div>
          <div class="box-body">
            <table class="table table-bitem_usersed table-hover">
              <tr>
                <th>Name</th>
                <th>E-mail</th>
                <th>
                  <i class="ion ion-edit"></i>
                </th>
                <th>
                  <i class="ion ion-trash-b"></i>
                </th>
              </tr>
              <% @users.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= link_to "", edit_user_path(user), { class: "ion ion-edit"} %></td>
                <td>
                    <%= link_to user_path(user), method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="ion ion-trash-b"></i>
                    <% end %>
                </td>
              </tr>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </section>  
</body>