config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#index'

  get '/show', to: 'home#show'

  resources :item_users
  resources :items
  resources :cupboards
  resources :users
  resources :user_sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]


  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  get '/sign_up', to: 'users#new', as: :sign_up #is this old/needed as xxxx?
  get '/new_cupboard', to: 'cupboards#new'
  put '/edit_cupboard', to: 'cupboards#edit'
 
 

  get 'renew/:id' => 'item_users#renew'
  get 'return/:id' => 'item_users#disable'


 
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_users, dependent: :destroy
  has_many :users, through: :item_users
  belongs_to :cupboard


  validates :name, presence: true
  validates :product_code, presence: true
  validates :description, presence: true
  validates :asset_type, presence: true
  validates :quantity, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :current_user_active
  
  def index
    @items = Item.all
    @item = Item.new

  end

  def new
    @item = Item.new
    @cupboards = Cupboard.all
  end

  def edit
    @cupboards = Cupboard.all
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path, notice: 'Item created.'
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to items_path, notice: 'Item updated.'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item destroyed.'
  end



  private
  
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:cupboard_id, :name, :category, :quantity, :description, :remaining_quantity, :product_code, :asset_type)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<body class="hold-transition skin-blue sidebar-mini">

<div class="content-wrapper">

  <section class="content-header">

  </section>
  <section class="content">
    <div class="row">
      <div class="col-md-12">
        <div class="box box-header">
          <div class="box-header with-border">
            <h3 class="box-title">Item Information</h3>
          </div>
          <%= form_for @item, method: "PUT" do |f| %>
            <% if @item.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

                <ul>
                <% @item.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="box-body">
             <div class="form-group">
                <label>Product code</label>
                <%= f.text_field :product_code, autocomplete: "off", placeholder: "Enter Full Name", class: "form-control", required: true %>
              </div>
             <div class="form-group">
                <label>Name</label>
                <%= f.text_field :name, autocomplete: "off", placeholder: "Enter Email Address", class: "form-control", required: true %>
              </div>

               <div class="form-group">
                <label>Description</label>
                <%= f.text_field :description, autocomplete: "off", placeholder: "Enter Full Name", class: "form-control", required: true %>
              </div>
             <div class="form-group">
                <label>Quantity</label>
                <%= f.text_field :quantity, autocomplete: "off", placeholder: "Enter Email Address", class: "form-control", required: true %>
              </div>
              <div class="form-group">
                <%= f.label :asset_type %>
                <%= f.select(:asset_type, [["Consumable","0"], ["Permanent","1"]], {}, { :class => 'form-control' })%>
              </div>
              <div class="form-group">
                <label>Cupboard</label>
                <%= f.select(:cupboard_id , options_from_collection_for_select(@cupboards, 'id', 'name', f.object.cupboard_id ), { include_blank: true }, { class: 'form-control', required: true }) %>
              </div>

            <div class="box-footer">
              <%= f.submit "Submit", class: "btn btn-primary"%>
            </div>
            <% end %>
        </div>
      </div>
    </div>
    </div>
  </section>

</div>
</body>

app/views/items/index.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <div class="content-wrapper">
      <section class="content-header">
        <h1>
          Items
        </h1>
       
      </section>


      <section class="content">
        <div class="row">
          <div class="col-xs-12">
            <div class="box">
              <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <td>Cupboard</td>
                      <th>Product Code</th>
                      <th>Name</th>
                      <th>Description</th>
                      <th>Quantity</th>
                      <% if current_user.is_admin? %>
                        <th>Edit</th>
                        <th>Delete</th>
                      <% end %>
                      <th>Borrow</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @items.each do |item| %>
                    <tr>
                      <td><%= item.id %></td>
                      <td><%= item.cupboard.name %></td>
                      <td><%= item.product_code %></td>
                      <td><%= item.name %></td>
                      <td><%= item.description %></td>
                      <td><%= item.quantity %></td>
                      <% if current_user.is_admin? %>
                        <td><%= link_to 'Edit', edit_item_path(item) %></td>
                        <td><%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure you want to delete this item?' } %></td>
                      <% end %>
                      <td><%= link_to 'Borrow', new_item_user_path(item_id: item.id) %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
                <%= link_to 'New Item', new_item_path %>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>

</body>

app/views/items/new.html.erb
<div class="col-md-12"><h1>New Item</h1>
<div class="jumbotron">
<%= render 'shared/errors', object: @item %>
<%= form_for @item do |f| %>
 
  <div class="form-group">
    <%= f.label :product_code %>
    <%= f.text_field :product_code, class: 'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :quantity %>
    <%= f.text_field :quantity, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :asset_type %>
    <%= f.select(:asset_type, [["Consumable","0"], ["Permanent","1"]], {}, { :class => 'form-control' })%>
  </div>
  <div class="form-group">
    <label>Cupboard</label>
    <%= f.select(:cupboard_id , options_from_collection_for_select(@cupboards, 'id', 'name' ), { include_blank: true }, { class: 'form-control', required: true }) %>
  </div>

  <%= f.submit 'Add Item', class: 'btn btn-primary btn-lg' %>
<% end %>
</div>
</div>