config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#index'

  get '/show', to: 'home#show'

  resources :item_users
  resources :items
  resources :cupboards
  resources :users
  resources :user_sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]


  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  get '/sign_up', to: 'users#new', as: :sign_up #is this old/needed as xxxx?
  get '/new_cupboard', to: 'cupboards#new'
  put '/edit_cupboard', to: 'cupboards#edit'
 
 

  get 'renew/:id' => 'item_users#renew'
  get 'return/:id' => 'item_users#disable'


 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cupboard.rb
class Cupboard < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :users


  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_users, dependent: :destroy
  has_many :users, through: :item_users
  belongs_to :cupboard


  validates :name, presence: true
  validates :product_code, presence: true
  validates :description, presence: true
  validates :asset_type, presence: true
  validates :quantity, presence: true
end

app/models/item_user.rb
class ItemUser < ApplicationRecord
  validate :quant_check
  belongs_to :item
  belongs_to :user

  validates :quantity, presence: true


  #Could be done using scopes READ UP
  def self.active?
    ItemUser.where(status: 1)
  end

  def self.inactive?
    ItemUser.where(status: 0)
  end

  def self.expired?
    ItemUser.where("expire_at < ?", Date.today).where(status: 1)
  end

  def self.renew id
    @item_user = ItemUser.where(id: id)
    @item_user.update(return_date: 2.days.from_now)
  end

  def self.disable id
    @item_user = ItemUser.where(id: id)
    @item_user.update(status: 0)
  end



private
  def quant_check
    if quantity > Item.find(item_id).quantity 
        self.errors.add(:quantity, :blank , message: "- Not enough stock")
    end
  end




  
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password, :password_confirmation

  has_many :item_users, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true


 
  acts_as_authentic do |c| 
    c.login_field = :email
     c.ignore_blank_passwords = true
     c.validate_password_field = false
     c.validate_email_field = false
      c.validate_login_field = false
      c.validate_password_field = false
    c.crypto_provider = Authlogic::CryptoProviders::SCrypt
  end
  
  def deliver_password_reset_instructions!
    reset_perishable_token!
    PasswordResetMailer.reset_email(self).deliver_now
  end

  scope :user_type, ->(user_type) { where("user_level = ?", user_type)}

  def is_admin?
    self.user_level == 1
  end


end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base


end

app/controllers/cupboards_controller.rb
class CupboardsController < ApplicationController
  before_action :current_user_active
  before_action :set_cupboard, except: [:new, :create]


  def new
    @cupboard = Cupboard.new
    @cupboards = Cupboard.all
    @user = current_user
    @users = User.all 
  end

  def create
    @cupboard = Cupboard.new(cupboard_params)
      if @cupboard.save
        flash[:notice] = "Cupboard successfuly added."
        redirect_to new_cupboard_path
      else
        render :new
      end
  end

  def show  
    @cupboards = Cupboard.all   
  end

  def edit

  end


  def update
   if @cupboard.update(cupboard_params);
     redirect_to new_cupboard_path, notice: 'Cupboard was successfully updated.'
   else
     render :edit
   end
  end

  def destroy
       @cupboard.destroy
       redirect_to new_cupboard_path, notice: 'Cupboard was successfully destroyed.'
  end


    private

    def cupboard_params
      params.require(:cupboard).permit( :name, :description)
    end 

    def set_cupboard
    @cupboard = Cupboard.find(params[:id])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :current_user_active


    def show  
      @user = current_user
      @item_users = ItemUser.all
      @items = Item.all
      @cupboards = Cupboard.all
      @users = User.all 
      #.includes(:XXX) preloads requested data 1 query at database not multiple!!
      @active = ItemUser.active?.includes(:item)     
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :current_user_active
  
  def index
    @items = Item.all
    @item = Item.new

  end

  def new
    @item = Item.new
    @cupboards = Cupboard.all
  end

  def edit
    @cupboards = Cupboard.all
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path, notice: 'Item created.'
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to items_path, notice: 'Item updated.'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item destroyed.'
  end



  private
  
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:cupboard_id, :name, :category, :quantity, :description, :remaining_quantity, :product_code, :asset_type)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def index
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :current_user_active, except: [:new, :create, :destroy]

  def new
  end

  def show
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticated(params[:password])
      session[:id] = user.id
      redirect_to session_path, notice: "#User:{user.id} logged in!"
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
  end

  def destroy
    if current_user.present?
      session.delete(:id)
      redirect_to login_path
    end
  end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user_active, except: [:new, :create, :destroy]
  before_action :set_user, except: [:new, :create]

  
  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
      if @user.save
        flash[:notice] = "Registration successful."
        redirect_to show_path
      else
        render :new
      end
  end

  def edit
  end  


  def update
   if @user.update(users_params);
     redirect_to show_path, notice: 'User was successfully updated.'
   else
     render :edit
   end
  end

  def destroy
    if @user.item_users.where(status: 1).count == 0
       @user.destroy
       redirect_to show_path, notice: 'Member was successfully destroyed.'
   else
      flash[:alert] = 'This user has active orders, please check items back in before trying to remove them from the system.'
      redirect_to show_path
    end
  end

  private

    def users_params
      params.require(:user).permit( :name, :email, :password, :user_level, :password_confirmation)
    end 

   def set_user
    @user = User.find(params[:id])
   end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cupboards_helper.rb
module CupboardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_users_helper.rb
module ItemUsersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stock</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div id="navbar">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path, class: "fa fa-home" %></li>
            <li><%= link_to 'Items', items_path, class: "fa fa-pencil" %></li>
            <li><%= link_to 'Users', users_path, class: "fa fa-pencil" %></li>
     
            <li><%= link_to 'Cupboards', new_cupboard_path, class: "fa fa-pencil" %></li>
           
          </ul>        
          <ul class="nav navbar-nav pull-right">
           
            <div class="nav navbar-nav">
              <% if current_user %>
                <div class="navemail">
                  <li><%= current_user.email %></li>
                  <li><%= link_to 'Sign Out', sign_out_path, method: :delete, class: "fa fa-sign-out" %></li>
                </div>
              <% else %>
                <li><%= link_to 'Sign In', sign_in_path, class: "fa fa-sign-in" %></li>
              <% end %>
            </div>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">

      <% flash.each do |key, value| %>

        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>

      <%= yield %>

     </div>


    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css" %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

  </div>

  <footer>
 
  </footer>
  </body>

app/views/pages/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome!</h1>
    <p>Sign up to get borrowing items.</p>
    <p>
      <%= link_to sign_up_path, class: 'btn btn-primary btn-lg' do %>
        Sign Up &raquo;
      <% end %>
    </p>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>